import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        surface: '#f6fafb',
        'surface-dim': '#d6dbdc',
        'surface-bright': '#f6fafb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f4f5',
        'surface-container': '#eaefef',
        'surface-container-high': '#e5e9ea',
        'surface-container-highest': '#dfe3e4',
        'on-surface': '#171c1d',
        'on-surface-variant': '#404849',
        'inverse-surface': '#2c3132',
        'inverse-on-surface': '#edf1f2',
        outline: '#70797a',
        'outline-variant': '#c0c8c9',
        'surface-tint': '#33666c',
        primary: '#306369',
        'on-primary': '#ffffff',
        'primary-container': '#4a7c82',
        'on-primary-container': '#f6feff',
        'inverse-primary': '#9ccfd6',
        secondary: '#516261',
        'on-secondary': '#ffffff',
        'secondary-container': '#d1e3e2',
        'on-secondary-container': '#556665',
        tertiary: '#625b51',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#7b7469',
        'on-tertiary-container': '#fffbff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#b8ecf2',
        'primary-fixed-dim': '#9ccfd6',
        'on-primary-fixed': '#001f23',
        'on-primary-fixed-variant': '#174e53',
        'secondary-fixed': '#d4e6e5',
        'secondary-fixed-dim': '#b8cac9',
        'on-secondary-fixed': '#0e1e1e',
        'on-secondary-fixed-variant': '#3a4a49',
        'tertiary-fixed': '#ebe1d4',
        'tertiary-fixed-dim': '#cfc5b9',
        'on-tertiary-fixed': '#1f1b13',
        'on-tertiary-fixed-variant': '#4c463c',
        background: '#f6fafb',
        'on-background': '#171c1d',
        'surface-variant': '#dfe3e4',
        'ocean-muted': '#5A8C92',
        'soft-mist': '#F4F7F7',
        'warm-sand': '#F9F6F2',
        'sage-highlight': '#8BA8A1',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '2rem',
        '3xl': '3rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1140px',
        base: '8px',
        'section-gap-desktop': '120px',
        'section-gap-mobile': '64px',
        gutter: '24px',
        'margin-mobile': '20px',
      },
      maxWidth: {
        'container-max': '1140px',
      },
      fontFamily: {
        headline: ['var(--font-manrope)', 'Manrope', 'sans-serif'],
        display: ['var(--font-manrope)', 'Manrope', 'sans-serif'],
        body: ['var(--font-open-sans)', 'Open Sans', 'sans-serif'],
        label: ['var(--font-open-sans)', 'Open Sans', 'sans-serif'],
        'headline-lg': ['var(--font-manrope)', 'Manrope', 'sans-serif'],
        'headline-md': ['var(--font-manrope)', 'Manrope', 'sans-serif'],
        'display-lg': ['var(--font-manrope)', 'Manrope', 'sans-serif'],
        'body-lg': ['var(--font-open-sans)', 'Open Sans', 'sans-serif'],
        'body-md': ['var(--font-open-sans)', 'Open Sans', 'sans-serif'],
        'label-md': ['var(--font-open-sans)', 'Open Sans', 'sans-serif'],
        caption: ['var(--font-open-sans)', 'Open Sans', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '1.4', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}

export default config
